from pathlib import Path
p=Path('app/src/main/java/com/ric/emuhub/MainActivity.kt')
s=p.read_text()

s=s.replace('    private var pendingArchiveSession: File? = null\n    private var allLibraryGames: List<GameEntry> = emptyList()', '    private var pendingArchiveSession: File? = null\n    private var pendingPs2ArchiveRomPath: String? = null\n    private var pendingPs2ArchiveRomName: String? = null\n    private var allLibraryGames: List<GameEntry> = emptyList()')

old='''        if (::status.isInitialized) {\n            val bios = Ps2BiosActivity.selectedBios(this)\n            if (bios != null && status.text.toString().startsWith("PS2 BIOS")) status.text = "PS2 BIOS ready • ${bios.name}"\n        }\n        if (::library.isInitialized && allLibraryGames.isNotEmpty()) {'''
new='''        if (::status.isInitialized) {\n            val bios = Ps2BiosActivity.selectedBios(this)\n            if (bios != null && status.text.toString().startsWith("PS2 BIOS")) status.text = "PS2 BIOS ready • ${bios.name}"\n            if (bios != null) resumePendingCompressedPs2()\n        }\n        if (::library.isInitialized && allLibraryGames.isNotEmpty()) {'''
if old not in s: raise SystemExit('onResume block not found')
s=s.replace(old,new)

old='''                    if(session.roms.size==1)launchExtractedRom(session,session.roms.first())\n                    else {\n                        val labels=session.roms.map{rom->"${archiveRomSystemLabel(rom)}  •  ${rom.displayName}"}.toTypedArray()\n                        AlertDialog.Builder(this).setTitle("Pilih game dari compressed file").setItems(labels){_,which->launchExtractedRom(session,session.roms[which])}.setNegativeButton("Batal"){_,_->session.root.deleteRecursively()}.setOnCancelListener{session.root.deleteRecursively()}.show()\n                    }'''
new='''                    val candidates=archiveGameCandidates(session)\n                    if(candidates.size==1)launchExtractedRom(session,candidates.first())\n                    else {\n                        val labels=candidates.map{rom->"${archiveRomSystemLabel(rom)}  •  ${rom.displayName}"}.toTypedArray()\n                        AlertDialog.Builder(this).setTitle("Pilih game dari compressed file").setItems(labels){_,which->launchExtractedRom(session,candidates[which])}.setNegativeButton("Batal"){_,_->session.root.deleteRecursively()}.setOnCancelListener{session.root.deleteRecursively()}.show()\n                    }'''
if old not in s: raise SystemExit('archive picker block not found')
s=s.replace(old,new)

insert='''\n    private fun archiveGameCandidates(session:ArchiveHelper.Session):List<ArchiveHelper.ExtractedRom>{\n        val biosLike=Regex("(?i)(^|[^a-z])(scph|ps2[_ -]?bios|bios[_ -]?ps2|rom0|rom1|erom|dvdrom)([^a-z]|$)")\n        val filtered=session.roms.filterNot{rom->\n            rom.ext=="bin" && biosLike.containsMatchIn(rom.displayName.substringBeforeLast('.',rom.displayName))\n        }\n        val base=if(filtered.isNotEmpty())filtered else session.roms\n        return base.sortedWith(compareBy<ArchiveHelper.ExtractedRom>{rom->\n            when(rom.ext){\n                "iso","cso","chd","xci","nsp","nro"->0\n                "cue","ecm"->1\n                "bin"->2\n                else->3\n            }\n        }.thenByDescending{it.file.length()}.thenBy{it.displayName.lowercase()})\n    }\n'''
marker='''\n    private fun archiveRomSystemLabel(rom:ArchiveHelper.ExtractedRom):String=when(rom.ext){'''
if marker not in s: raise SystemExit('archive label marker not found')
s=s.replace(marker,insert+marker)

old='''    private fun launchExtractedPs2OrSetup(session:ArchiveHelper.Session,rom:ArchiveHelper.ExtractedRom){\n        if(Ps2BiosActivity.selectedBios(this)==null){\n            status.text="PS2 BIOS belum siap • game belum dijalankan"\n            AlertDialog.Builder(this)\n                .setTitle("PS2 BIOS diperlukan")\n                .setMessage("Compressed game sudah berhasil dibuka, tapi ARMSX2 membutuhkan BIOS PS2. Game tidak akan dialihkan otomatis ke layar BIOS.")\n                .setPositiveButton("SETUP BIOS"){_,_->startActivity(Intent(this,Ps2BiosActivity::class.java))}\n                .setNegativeButton("Batal"){_,_->session.root.deleteRecursively()}\n                .setOnCancelListener{session.root.deleteRecursively()}\n                .show()\n            return\n        }\n        pendingArchiveSession=session.root\n        startActivityForResult(Intent(this,Ps2GameActivity::class.java).putExtra("romPath",rom.file.absolutePath).putExtra("romName",rom.displayName),REQUEST_ARCHIVE_GAME)\n    }'''
new='''    private fun launchExtractedPs2OrSetup(session:ArchiveHelper.Session,rom:ArchiveHelper.ExtractedRom){\n        if(Ps2BiosActivity.selectedBios(this)==null){\n            pendingArchiveSession=session.root\n            pendingPs2ArchiveRomPath=rom.file.absolutePath\n            pendingPs2ArchiveRomName=rom.displayName\n            status.text="PS2 BIOS diperlukan • game akan lanjut otomatis setelah BIOS siap"\n            AlertDialog.Builder(this)\n                .setTitle("PS2 BIOS diperlukan")\n                .setMessage("Game PS2 sudah dipilih dari compressed file. Setup BIOS sekali; saat kembali ke Emu Hub game ini akan langsung dilanjutkan, bukan kembali memilih file.")\n                .setPositiveButton("SETUP BIOS"){_,_->startActivity(Intent(this,Ps2BiosActivity::class.java))}\n                .setNegativeButton("Batal"){_,_->clearPendingCompressedPs2(true)}\n                .setOnCancelListener{clearPendingCompressedPs2(true)}\n                .show()\n            return\n        }\n        pendingArchiveSession=session.root\n        pendingPs2ArchiveRomPath=null\n        pendingPs2ArchiveRomName=null\n        startActivityForResult(Intent(this,Ps2GameActivity::class.java).putExtra("romPath",rom.file.absolutePath).putExtra("romName",rom.displayName),REQUEST_ARCHIVE_GAME)\n    }\n\n    private fun resumePendingCompressedPs2(){\n        val path=pendingPs2ArchiveRomPath?:return\n        val root=pendingArchiveSession?:return\n        val file=File(path)\n        if(!root.exists()||!file.isFile){clearPendingCompressedPs2(true);return}\n        val name=pendingPs2ArchiveRomName?:file.name\n        pendingPs2ArchiveRomPath=null\n        pendingPs2ArchiveRomName=null\n        status.text="PS2 BIOS ready • launching $name"\n        startActivityForResult(Intent(this,Ps2GameActivity::class.java).putExtra("romPath",file.absolutePath).putExtra("romName",name),REQUEST_ARCHIVE_GAME)\n    }\n\n    private fun clearPendingCompressedPs2(deleteSession:Boolean){\n        pendingPs2ArchiveRomPath=null\n        pendingPs2ArchiveRomName=null\n        if(deleteSession){pendingArchiveSession?.deleteRecursively();pendingArchiveSession=null}\n    }'''
if old not in s: raise SystemExit('PS2 compressed block not found')
s=s.replace(old,new)

old='''        if(requestCode==REQUEST_ARCHIVE_GAME){pendingArchiveSession?.deleteRecursively();pendingArchiveSession=null;status.text="Temporary archive files deleted";return}'''
new='''        if(requestCode==REQUEST_ARCHIVE_GAME){clearPendingCompressedPs2(true);status.text="Temporary archive files deleted";return}'''
if old not in s: raise SystemExit('activity result archive block not found')
s=s.replace(old,new)

p.write_text(s)
print('patched MainActivity compressed routing')
