from pathlib import Path
p=Path('app/src/main/cpp/emuhost.cpp')
s=p.read_text()
s=s.replace('static ANativeWindow* nativeWindow=nullptr; static bool directWindowSurface=false;', 'static ANativeWindow* nativeWindow=nullptr; static bool directWindowSurface=false;\nstatic GLuint directFbo=0,directColor=0,directDepth=0; static int directFboW=1024,directFboH=1024;')
s=s.replace('static bool makeHwCurrent(){return hwEnabled&&eglDisplay!=EGL_NO_DISPLAY&&eglSurface!=EGL_NO_SURFACE&&eglContext!=EGL_NO_CONTEXT&&eglMakeCurrent(eglDisplay,eglSurface,eglSurface,eglContext)==EGL_TRUE;} static void releaseHwCurrent(){if(eglDisplay!=EGL_NO_DISPLAY)eglMakeCurrent(eglDisplay,EGL_NO_SURFACE,EGL_NO_SURFACE,EGL_NO_CONTEXT);} static uintptr_t hwFramebuffer(){return 0;}', 'static bool makeHwCurrent(){return hwEnabled&&eglDisplay!=EGL_NO_DISPLAY&&eglSurface!=EGL_NO_SURFACE&&eglContext!=EGL_NO_CONTEXT&&eglMakeCurrent(eglDisplay,eglSurface,eglSurface,eglContext)==EGL_TRUE;} static void releaseHwCurrent(){if(eglDisplay!=EGL_NO_DISPLAY)eglMakeCurrent(eglDisplay,EGL_NO_SURFACE,EGL_NO_SURFACE,EGL_NO_CONTEXT);} static uintptr_t hwFramebuffer(){return (isDolphin&&directWindowSurface&&directFbo)?directFbo:0;}')
s=s.replace('if(readbackPbo[0]){glDeleteBuffers(2,readbackPbo);readbackPbo[0]=readbackPbo[1]=0;readbackPboBytes=0;}if(hwContextDestroy', 'if(readbackPbo[0]){glDeleteBuffers(2,readbackPbo);readbackPbo[0]=readbackPbo[1]=0;readbackPboBytes=0;}if(directFbo){glDeleteFramebuffers(1,&directFbo);directFbo=0;}if(directColor){glDeleteTextures(1,&directColor);directColor=0;}if(directDepth){glDeleteRenderbuffers(1,&directDepth);directDepth=0;}if(hwContextDestroy')
needle='glViewport(0,0,1024,1024);glClearColor(0,0,0,1);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);glFinish();releaseHwCurrent();traceLine("hw: EGL context registered");return true;}'
repl='''if(isDolphin&&directWindowSurface){\n glGenFramebuffers(1,&directFbo); glBindFramebuffer(GL_FRAMEBUFFER,directFbo);\n glGenTextures(1,&directColor); glBindTexture(GL_TEXTURE_2D,directColor); glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,directFboW,directFboH,0,GL_RGBA,GL_UNSIGNED_BYTE,nullptr); glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR); glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR); glFramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,directColor,0);\n glGenRenderbuffers(1,&directDepth); glBindRenderbuffer(GL_RENDERBUFFER,directDepth); glRenderbufferStorage(GL_RENDERBUFFER,GL_DEPTH24_STENCIL8,directFboW,directFboH); glFramebufferRenderbuffer(GL_FRAMEBUFFER,GL_DEPTH_STENCIL_ATTACHMENT,GL_RENDERBUFFER,directDepth);\n if(glCheckFramebufferStatus(GL_FRAMEBUFFER)!=GL_FRAMEBUFFER_COMPLETE){traceLine("hw: direct FBO incomplete");destroyHw();return false;} traceLine("hw: direct FBO ready");\n}\n glBindFramebuffer(GL_FRAMEBUFFER,hwFramebuffer());glViewport(0,0,1024,1024);glClearColor(0,0,0,1);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);glFinish();releaseHwCurrent();traceLine("hw: EGL context registered");return true;}'''
if needle not in s: raise SystemExit('createHw needle missing')
s=s.replace(needle,repl)
old='if(isDolphin&&directWindowSurface){frameW=w;frameH=h;eglSwapBuffers(eglDisplay,eglSurface);return;}'
new='''if(isDolphin&&directWindowSurface){frameW=w;frameH=h;EGLint sw=0,sh=0;eglQuerySurface(eglDisplay,eglSurface,EGL_WIDTH,&sw);eglQuerySurface(eglDisplay,eglSurface,EGL_HEIGHT,&sh);glBindFramebuffer(GL_READ_FRAMEBUFFER,directFbo);glBindFramebuffer(GL_DRAW_FRAMEBUFFER,0);glBlitFramebuffer(0,0,(GLint)w,(GLint)h,0,0,sw,sh,GL_COLOR_BUFFER_BIT,GL_LINEAR);glBindFramebuffer(GL_FRAMEBUFFER,directFbo);if(eglSwapBuffers(eglDisplay,eglSurface)!=EGL_TRUE)traceLine("video: eglSwapBuffers failed");return;}'''
if old not in s: raise SystemExit('capture needle missing')
s=s.replace(old,new)
p.write_text(s)

# preserve NativeBridge/GameActivity from prior direct patch, only native FBO presentation changes
print('patched Dolphin frontend FBO -> window surface blit')
